### PR TITLE
Dec8commit1

### PR DESCRIPTION
**Pull request by netapp-dorianh**

### CODE REVIEW

**Review by adamn-ntap — COMMENTED** [review]
Checking on something... 

All of the page summaries (other than one) begin with “This section… “.

These summaries show up in the search result previews. I think our standard is “This page…”. Is this variant by design?

**Comment by netapp-dorianh** [comment]
Hello Adam,

I was unaware of the standard. I will be happy to change it to Page.

Cheers,

Dorian

**Comment by adamn-ntap** [comment]
Thanks for being flexible, Dorian. I'm pretty sure I'm not leading you down the primrose path. Can you check to make sure I'm not wrong? Maybe sample a bunch of the .adoc in the occm repo?

**Comment by netapp-dorianh** [comment]
Will do.

**Comment by netapp-dorianh** [comment]
I did a quick check of the occm repo, and they do not use “this section” or “this page” in any of their summaries. Rather, the summary starts with a description of the content. For example:

“Backup to Cloud is an add-on service for Cloud Volumes ONTAP and on-premises ONTAP clusters that delivers backup and restore capabilities for protection, and long-term archive of your cloud data. Backups are stored in an object store in your cloud account, independent of volume Snapshot copies used for near-term recovery or cloning.”

I presume that this is the format that I should follow.

D

From: Henderson, Dorian
Sent: Tuesday, December 8, 2020 5:01 PM
To: NetAppDocs/ontap-whatsnew <reply@reply.github.com>; NetAppDocs/ontap-whatsnew <ontap-whatsnew@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Subject: RE: [NetAppDocs/ontap-whatsnew] Dec8commit1 (#5)

Will do.

**Pull request merged**
